name: Amazon Test Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  E2E-Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          command: npm run cy:run
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: e2e-test-report
            path: |
              cypress/reports/html/index.html