name: Amazon Test Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  E2E-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge, electron]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Cache node modules
        uses: actions/cache@v3.2.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        with:
          browser: ${{ matrix.browser }}
          command: npm run cy:run
          
      - name: Generate report
        if: always()
        run: npm run mochawesome:merge

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report-${{ matrix.browser }}-${{ github.run_id }}
          path: |
            mochawesome.json
            mochawesome-report/**
